### ISSUE TITLE
org_create_assignment() calls deprecated function...

### ISSUE THREAD

**Issue by pefreeman** [rundel/ghclass#111]
A non-critical FYI. When I run org_create_assignment(), I see the following (after it runs successfully):

Warning message:
'repo_mirror' is deprecated.
Use 'repo_mirror_template' instead.

I call the function as it is called in the 2019 JSM talk slides: org, repo, user, and source_repo set, with other arguments set to default values.

**Comment by rundel** [comment]
Thanks for pointing this out, I hadn't thought this process through - the deprecation warning is due to ghclass moving to favor GitHub's use of template repos (this makes copying repos much easier and faster). 

I can definitely and a more useful and informative warning in the context of `org_create_assignment()`.
