### ISSUE TITLE
Team organization only seems to work if the teams are created with ghclass? 

### ISSUE THREAD

**Issue by norcalbiostat** [rundel/ghclass#130]
If I use `team_create("DATA485-S22",c("hw1-team01","hw1-team02"))` then `team_delete("DATA485-S22",c("hw1-team01","hw1-team02"))` will work. 

But if the team was created using github classroom where students check out a team assignment where they specify what team they are on, I can't seem to delete the teams. It doesn't return an error, it just has no effect. Am I missing something?

**Comment by rundel** [comment]
I'm not an expert on github classroom and it has been a few years since I last used it but I believe the issue is that it doesn't actually use organization teams, it just adds the students as outside collaborators to the repository. You should be able to use `ghclass::repo_remove_user()` to drop them from the repository or `ghclass::repo_user_permission()` to change their access level.

If this is not the case do let me know.

**Comment by norcalbiostat** [comment]
Yea, that works. 
Okay so it sounds like you don't use the web interface for github classroom to distribute assignments then. `ghclass` can take care of all of the same sort of class management as sending out that assignment invite link through github classroom does.
