### ISSUE TITLE
add_files() doesn't upload local file

### ISSUE THREAD

**Issue by thereseanders** [rundel/ghclass#16]
add_files() does not upload local files to a repository. For example, the code below

`add_files(get_repos("ghclass-test","base_hw1"),
message = "Adding files for HW1",
files = "~/Documents/RStudio/hw1_sample_190529.Rmd")`

adds a text file called "hw1_sample_190529.Rmd" with the content "~/Documents/RStudio/hw1_sample_190529.Rmd", not the actual local R Markdown doc.

<img width="994" alt="image" src="https://user-images.githubusercontent.com/26805373/58647443-6f0b8800-82bc-11e9-9f39-08cb63a71126.png">

Should add_files() use something like httr::upload_file()?

**Comment by rundel** [comment]
Definitely a bug, I think I have it fixed now. I've also renamed the arguments to the put_file function to make things a big clearer about what the arguments actually do.

I need to think about the design more generally and what is exported and at what level since rundel/wercker currently needs `put_file` but it is not really meant to be user facing.

**Comment by thereseanders** [comment]
Thank you! The new argument names are much clearer. I kept confusing myself when working on this earlier.
