### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by thereseanders** [rundel/ghclass#21]
With all the changes that we are making to `ghclass`, how can we ensure backwards compatibility? 

Current examples
- `check_repos()`changed to `check_repo` (i.e. singular names for all functions).
- Changing `repo` parameter from having to be in format "owner/name" to separate `owner` and `reponame` parameters.
- changing `org` parameter to `owner` throughout the package.

**Comment by rundel** [comment]
Since there hasn't been an official cran release we can play a bit fast and loose with making breaking changes at this point. In the case of changing function names we can include the old function along with a call to .Deprecated to indicate that it is going away.

Specifically for something like check_repos that is also mostly an internally used function so not much harm in changing it.

**Comment by thereseanders** [comment]
I will implement the call to .Deprecated whenever appropriate.
